### ISSUE TITLE
MenuSystem tm;

### ISSUE THREAD

**Issue by rusty91** [hestenet/arduino-shot-timer#7]
I am getting:

no matching function for call to 'MenuSystem::MenuSystem()'

When trying to compile.

**Comment by hestenet** [comment]
Thanks for the issue report, Rusty.

I haven't looked at this in quite a while, and it gave me a reason to download the Arduino IDE again. 

I've just downloaded it - downloaded the 2.0.0 release - and compiled, and it works for me.

My best guess is that what's going wrong for you is some kind of version mismatch:

- [ ] What version of the IDE are you using? Should be 1.8.2
- [ ] Do you have all the libraries properly installed using: Sketch -> Include Library -> Manage Libraries? (especially arduino-menusystem?) 

Here's a list of all the non-built-in libraries my sketch uses, and which version of each:

- [ ] <MenuSystem.h> v. 2.1.1
- [ ] <Chrono.h> v. 1.0.0 
- [ ] <PGMWrap.h> v. 1.0.0
- [ ] <EEWrap.h> v. 1.0.0
- [ ] <Adafruit_RGBLCDShield.h> v.1.0.1

I hope this helps!

**Comment by rusty91** [comment]
Thanks for the quick reply!

I do have all of those installed, except I had v.1.0.2 of the Adafruit_RGBLCDShield.h installed so I went back to v.1.0.1 but that didn't fix the issue.

Since I was having issue with the MenuSystem I rolled back to v2.1.0 and that appeard to fix my issue.

**Comment by rusty91** [comment]
Also, I see you have the mic on pin A0.  I am not finding a variable for the piezo though, what variable is the piezo and what pin did you use it on?  I know I can switch it to whatever pin I want,  I just can't find where to assign it.

**Comment by hestenet** [comment]
If I remember correctly the piezzo buzzer is using the default pinouts from the ToneAC library - 9&10 for the Uno:
https://bitbucket.org/teckel12/arduino-toneac/wiki/Home#!connection-example

**Comment by rusty91** [comment]
Awesome, thank you!  

I will let you know when I have a case made for this!

**Comment by hestenet** [comment]
Fantastic! Thank you for doing this. Making any kind of enclosure is not really something I have any idea how to do.
